name: test dev

on:
  workflow_dispatch:
  release:
    types:
      - published


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v6
      # ===== 生成仓库索引 =====
      - name: Generate repository index
        run: |
          set -euo pipefail
          TARGET_DIR="./opkg-script"
          mkdir -p "$TARGET_DIR"

          RETRY_OPTS="--retry 5 --retry-delay 2 --retry-max-time 60"
          URL_BASE="https://git.yoctoproject.org/opkg-utils/plain"

          # 循环下载，代码更整洁
          for file in opkg-make-index opkg.py arfile.py; do
            echo "Downloading $file..."
            curl -v -fL $RETRY_OPTS "$URL_BASE/$file" -o "$TARGET_DIR/$file"
          done

          # 直接修改目标目录下的权限
          chmod 0755 "$TARGET_DIR/opkg-make-index"
          chmod 0644 "$TARGET_DIR/opkg.py"
          chmod 0644 "$TARGET_DIR/arfile.py"

          ls -al "$TARGET_DIR/"

          echo "📦 Generating opkg index..."
          $TARGET_DIR/opkg-make-index --help
          ls -al